<?php 
// Code
?>
<div class="row">
	<div class="col-md-12">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $this->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Calculate')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Input 1')) ?></span></label>
                            <div class="control">
                                <input name="inputleft" id="inputleft" title="Input Left" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-number':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Math Operation')) ?></span></label>
                            <div class="control">
                                <select name="operation" id="operation" title="Math Operation" value="" class="validate-select"
                                       data-validate="{required:true}" >
                                       	<option value="plus">Plus (+)</option>
                                       	<option value="minus">Minus (-)</option>
                                       	<option value="multiply">Multiply (x)</option>
                                       	<option value="divide">Divide (/)</option>
                                    </select>
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Input 2')) ?></span></label>
                            <div class="control">
                                <input name="inputright" id="inputright" title="Input Right" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-number':true}">
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                	<input type="hidden" name="customer_id" id="customer_id" value="<?php echo $this->getCustomerId(); ?>" />
                    <button type="submit" class="action submit primary" title="Submit"><span><?= $block->
                        escapeHtmlAttr(__('Submit')) ?></span></button>
                </div>
                <div class="secondary">
			        <a class="action back" href="<?= $block->escapeUrl($block->getUrl('customer/calculation/history')) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
			    </div>
            </div>
        </form>
    </div>
</div>
